### ISSUE TITLE
0-overview.ipynb uses data that is not yet fetched

### ISSUE THREAD

**Issue by tacaswell** [coiled/pydata-global-dask#10]
The other notebooks have a `%run prep-.py -d flights` (as does your video), but it is not in the notebooks that are launched via binder.

This has confused at least 1 person (this is a proxy bug report).

**Comment by jrbourbeau** [comment]
Ah, thank you @tacaswell! We added that cell when recording, but I forgot to push it up to the repo here. I'll do that right now

**Comment by jrbourbeau** [comment]
Thanks again for reporting @tacaswell! I just merged https://github.com/coiled/pydata-global-dask/pull/11 which adds the `%run prep-.py -d flights` cell to `0-overview.ipynb`
