### ISSUE TITLE
Review overview and delayed notebooks

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/pydata-global-dask#3]
@hugobowne when you get a chance could you review and propose/make edits for the [overview](https://github.com/coiled/pydata-global-dask/blob/master/0-overview.ipynb) and [delayed](https://github.com/coiled/pydata-global-dask/blob/master/1-delayed.ipynb) notebooks

**Comment by jrbourbeau** [comment]
Just added a [DataFrame notebook](https://github.com/coiled/pydata-global-dask/blob/master/2-dataframe.ipynb) too

**Comment by hugobowne** [comment]
i've responded in issues #6 and #8 so I'll close this. Re-open if necessary.
