### ISSUE TITLE
Binder inconsistent

### ISSUE THREAD

**Issue by hugobowne** [coiled/pydata-global-dask#7]
First it didn't work:

![Screen Shot 2020-10-15 at 12 21 14 pm](https://user-images.githubusercontent.com/4182382/96077384-63ddea00-0efb-11eb-970f-ae66024558a0.png)

And then it worked!

![Screen Shot 2020-10-15 at 3 28 49 pm](https://user-images.githubusercontent.com/4182382/96077329-37c26900-0efb-11eb-9038-0e27b07eee76.png)

**Comment by jrbourbeau** [comment]
Hrm, I've launched binder a few times and haven't been able to reproduce the "Directory not found" issue : / I'm not sure what can be done on our side to resolve that

**Comment by hugobowne** [comment]
Happy to close and re-open if necessary
